from typing import TypedDict, List, Dict, Any, Optional
from pydantic import BaseModel

class AgentState(TypedDict):
    """
    The state dictionary that will be passed between all LangGraph agents.
    """
    # Provided by the upload/ingestion phase
    dataset_metadata: Dict[str, Any]
    
    # Decided by the Supervisor Agent
    task_type: Optional[str]  # e.g., 'classification', 'regression', 'clustering'
    target_column: Optional[str]
    execution_plan: List[str]
    
    # Decided/Generated by Data Analyst Agent
    eda_results: Dict[str, Any]
    
    # Decided/Generated by Data Engineer Agent
    features_engineered: List[str]
    
    # Decided by Human in the loop
    requires_human_approval: bool
    human_feedback: Optional[str]
    
    # Generated by ML Engineer Agent
    models_evaluated: List[Dict[str, Any]]
    best_model: Optional[str]
